import { Character } from './types';

export const INITIAL_CHARACTERS: Character[] = [
  {
    id: 'c1',
    name: '김부장',
    role: '부장',
    traits: ['꼰대', '등산 애호가', '잔소리꾼'],
    status: '기혼',
    relationships: { 'c2': 10, 'c3': 20, 'c4': -10, 'c5': 5 },
    imageUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Kim&clothing=blazerAndShirt&facialHair=moustacheFancy',
    catchphrase: "나 때는 말이야~ 에잉 쯧쯧.",
    age: 52,
    birthday: '04-15',
    height: 172,
    mbti: 'ESTJ',
    likes: ['등산', '믹스커피', '회식'],
    dislikes: ['MZ세대', '재택근무', '야채'],
    isEmployed: true,
  },
  {
    id: 'c2',
    name: '이과장',
    role: '과장',
    traits: ['일잘러', '커피 중독', '냉소적'],
    status: '싱글',
    relationships: { 'c1': -20, 'c3': 30, 'c4': 10, 'c5': 0 },
    imageUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Lee&clothing=collarAndSweater&accessories=glasses',
    catchphrase: "그래서 결론이 뭡니까? 효율적으로 합시다.",
    age: 38,
    birthday: '11-02',
    height: 178,
    mbti: 'INTJ',
    likes: ['아메리카노', '조용한 곳', '주식'],
    dislikes: ['야근', '소음', '김부장'],
    isEmployed: true,
  },
  {
    id: 'c3',
    name: '박대리',
    role: '대리',
    traits: ['분위기 메이커', '오지랖', '금사빠'],
    status: '싱글',
    relationships: { 'c1': 30, 'c2': 20, 'c4': 40, 'c5': 15 },
    imageUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Park&top=longHair',
    catchphrase: "어머 대박! 이거 들었어요? 오늘 점심 뭐 먹죠?",
    age: 32,
    birthday: '07-20',
    height: 165,
    mbti: 'ENFP',
    likes: ['맛집 투어', '인스타그램', '수다'],
    dislikes: ['지루한 것', '비오는 날', '배고픔'],
    isEmployed: true,
  },
  {
    id: 'c4',
    name: '최사원',
    role: '신입 사원',
    traits: ['MZ세대', '눈치 없음', '칼퇴 요정'],
    status: '연애 중',
    relationships: { 'c1': -30, 'c2': 0, 'c3': 10, 'c5': 20 },
    imageUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Choi&clothing=hoodie',
    catchphrase: "저 6시라서 퇴근해보겠습니다. 에어팟 껴도 되나요?",
    age: 27,
    birthday: '01-10',
    height: 181,
    mbti: 'ISTP',
    likes: ['게임', '에어팟', '퇴근'],
    dislikes: ['회식', '전화 업무', '잔소리'],
    isEmployed: true,
  },
  {
    id: 'c5',
    name: '정인턴',
    role: '인턴',
    traits: ['열정 만수르', '실수투성이', '순수함'],
    status: '싱글',
    relationships: { 'c1': 40, 'c2': 5, 'c3': 10, 'c4': 15 },
    imageUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Jung&clothing=overall',
    catchphrase: "열심히 하겠습니다! ...앗, 죄송합니다!",
    age: 24,
    birthday: '05-05',
    height: 160,
    mbti: 'ISFJ',
    likes: ['칭찬', '다이어리 꾸미기', '간식'],
    dislikes: ['실수', '혼나는 것', '매운 음식'],
    isEmployed: true,
  },
];

export const MAX_RELATIONSHIP = 100;
export const MIN_RELATIONSHIP = -100;